
-- Script de Depuración Profunda para el Registro de Usuarios

-- 1. Crear tabla de logs para ver qué pasa "dentro" de la base de datos
CREATE TABLE IF NOT EXISTS public.debug_logs (
  id bigint generated by default as identity primary key,
  message text,
  details jsonb,
  created_at timestamp with time zone default now()
);

-- Habilitar acceso a logs
ALTER TABLE public.debug_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public logs insert" ON public.debug_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Public logs select" ON public.debug_logs FOR SELECT USING (true);
GRANT ALL ON TABLE public.debug_logs TO anon, authenticated, service_role;

-- 2. Modificar Trigger para Escribir Logs
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Log de inicio
  INSERT INTO public.debug_logs (message, details)
  VALUES ('Trigger handle_new_user iniciado', jsonb_build_object('user_id', new.id, 'email', new.email, 'metadata', new.raw_user_meta_data));

  BEGIN
    INSERT INTO public.profiles (
      id, 
      username, 
      email, 
      role, 
      full_name,
      address,
      dni,
      phone,
      updated_at
    )
    VALUES (
      new.id,
      new.email,
      new.email,
      'user',
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'address',
      new.raw_user_meta_data->>'dni',
      new.raw_user_meta_data->>'phone',
      NOW()
    );

    -- Log de éxito
    INSERT INTO public.debug_logs (message, details)
    VALUES ('Trigger handle_new_user ÉXITO', jsonb_build_object('user_id', new.id));

  EXCEPTION WHEN OTHERS THEN
    -- Log de error
    INSERT INTO public.debug_logs (message, details)
    VALUES ('Trigger handle_new_user ERROR', jsonb_build_object('error', SQLERRM, 'state', SQLSTATE));
    
    RAISE WARNING 'Error en handle_new_user: %', SQLERRM;
  END;
  RETURN new;
END;
$$;
