-- 1. Tabla de Perfiles (Extiende la info de usuario)
-- Se vincula automáticamente cuando un usuario se registra
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  full_name text,
  address text,
  dni text,
  phone text,
  role text default 'user',
  updated_at timestamp with time zone
);

-- 2. Tabla de Pedidos
create table public.orders (
  id uuid default gen_random_uuid() primary key,
  user_id_ref text, -- Por ahora guardamos el username/id de referencia
  total numeric,
  status text default 'pending', -- pending, paid, shipped, delivered
  delivery_date date,
  payment_method text,
  invoice_number text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Tabla de Items del Pedido
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade,
  product_id text,
  quantity integer,
  price_at_purchase numeric
);

-- 4. Tabla de Inventario
create table public.inventory (
  product_id text primary key,
  stock_quantity integer default 0,
  min_stock_alert integer default 10,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Insertar stock inicial para los productos base
insert into public.inventory (product_id, stock_quantity) values 
('carton-xxl', 100), ('carton-l', 100), ('carton-m', 100);

-- 5. Políticas de Seguridad (RLS)
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory enable row level security;

-- Perfiles
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert own profile" on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- Pedidos (ADMIN puede ver todo, USER solo lo suyo)
create policy "Admins can see all orders" 
  on orders for select 
  using ( (select role from profiles where id = auth.uid()) = 'admin' );

create policy "Users can see their own orders" 
  on orders for select 
  using ( user_id_ref = auth.jwt() ->> 'email' );

create policy "Admin can update orders status"
  on orders for update
  using ( (select role from profiles where id = auth.uid()) = 'admin' );

create policy "Anyone can create orders" on orders for insert with check ( true );

-- Items de Pedido
create policy "Admins can see all order items" on order_items for select using ( (select role from profiles where id = auth.uid()) = 'admin' );
create policy "Users can see own items" on order_items for select using ( true ); -- Simplificado para demo
create policy "Anyone can insert items" on order_items for insert with check ( true );

-- Inventario (Solo ADMIN)
create policy "Anyone can view inventory" on inventory for select using ( true );
create policy "Only admins can update inventory" 
  on inventory for update 
  using ( (select role from profiles where id = auth.uid()) = 'admin' );


-- 6. Automatización de Perfiles (Trigger)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, full_name, role, email)
  values (
    new.id,
    new.email, -- Usamos email como username base inicial
    new.raw_user_meta_data->>'full_name',
    'user', -- Por defecto todos son 'user'
    new.email
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger que se dispara cada vez que un usuario se crea en auth.users
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 7. Script para crear/promover ADMIN (Ejecutar manualmente en SQL Editor de Supabase)
/*
-- Opción A: Si el usuario ya existe, actualizar su rol
update public.profiles 
set role = 'admin' 
where email = 'GranHuevon'; -- O el email que uses para admin

-- Opción B: Insertar usuario 'GranHuevon' manualmente en auth.users es complejo desde SQL puro 
-- debido a contraseñas hasheadas. Es mejor registrarse en el frontend y luego correr el Update de arriba.
*/
