-- SCRIPT DE CORRECCIÓN DE PERMISOS (RLS)
-- Ejecuta esto en el Editor SQL de Supabase para permitir que la web lea los datos.

-- 1. Habilitar lectura de PERFILES para todos (necesario para ver lista de usuarios)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);

-- 2. Habilitar lectura de PEDIDOS para todos (o solo admin, simplificado a todos por ahora)
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Orders are viewable by everyone" ON orders;
CREATE POLICY "Orders are viewable by everyone" ON orders FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert their own orders" ON orders;
CREATE POLICY "Users can insert their own orders" ON orders FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Users can update their own orders" ON orders;
CREATE POLICY "Users can update their own orders" ON orders FOR UPDATE USING (true);


-- 3. Habilitar lectura de ITEMS DE PEDIDO
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Order items are viewable by everyone" ON order_items;
CREATE POLICY "Order items are viewable by everyone" ON order_items FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert order items" ON order_items;
CREATE POLICY "Users can insert order items" ON order_items FOR INSERT WITH CHECK (true);

-- 4. Habilitar lectura de INVENTARIO
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Inventory is viewable by everyone" ON inventory;
CREATE POLICY "Inventory is viewable by everyone" ON inventory FOR SELECT USING (true);

-- 5. Debug / Logs (si usas esta tabla)
CREATE TABLE IF NOT EXISTS debug_logs (
    id bigint generated by default as identity primary key,
    message text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE debug_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Debug logs viewable by everyone" ON debug_logs FOR SELECT USING (true);
CREATE POLICY "Insert logs" ON debug_logs FOR INSERT WITH CHECK (true);
